# Generated by Django 5.1.4 on 2025-02-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
