# Generated by Django 5.1.4 on 2025-02-02 04:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_remove_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='ttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
