# Generated by Django 5.1.4 on 2025-02-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_cart_qty_cart_ttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
